version: "3.9"

services:
  db:
    image: postgres
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
    ports:
      - 8080:8080
    env_file:
      - ./.env.web
    depends_on:
      - db

  nginx:
    build: ./nginx
    volumes:
    - static_volume:/home/app/web/staticfiles
    - media_volume:/home/app/web/media
    ports:
    - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: